"""Students simulated from known BKT parameters.

Used by the tests and ``demo.py``: when the data really were generated by a
BKT process, EM has a correct answer to recover.
"""

from __future__ import annotations

import numpy as np

from .data import COLLAPSED, Log


def simulate_bkt(
    params: dict[str, list[float]],
    n_students: int,
    attempts_per_skill: int,
    seed: int = 0,
    interleave: bool = True,
) -> Log:
    """Each student practises every skill ``attempts_per_skill`` times.

    ``params`` maps prior/learn/guess/slip to one value per skill. With
    ``interleave`` the skills are practised in a random order per student,
    otherwise in blocks.
    """
    rng = np.random.default_rng(seed)
    n_skills = len(params["prior"])
    p = {k: np.asarray(v, dtype=np.float64) for k, v in params.items()}
    user, skill, correct = [], [], []
    for u in range(n_students):
        plan = np.repeat(np.arange(n_skills), attempts_per_skill)
        if interleave:
            rng.shuffle(plan)
        known = rng.random(n_skills) < p["prior"]
        for s in plan:
            ok = rng.random() >= p["slip"][s] if known[s] else rng.random() < p["guess"][s]
            user.append(u)
            skill.append(s)
            correct.append(int(ok))
            if not known[s] and rng.random() < p["learn"][s]:
                known[s] = True
    n = len(user)
    sk = np.asarray(skill, dtype=np.int32)
    return Log(
        name="synthetic",
        variant=COLLAPSED,
        user=np.asarray(user, dtype=np.int32),
        item=sk.copy(),
        skill=sk,
        correct=np.asarray(correct, dtype=np.int8),
        attempt=np.arange(n, dtype=np.int64),
        skill_names=[f"skill-{i}" for i in range(n_skills)],
        item_names=[f"item-{i}" for i in range(n_skills)],
        user_names=[f"student-{i}" for i in range(n_students)],
    )
